version: '3.8'
services:
  sqlserver:
    build: .
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "TuPasswordSegura123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data:
